version: '3'
services:
  prova:
    build: .docker/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../:/prova
    ports:
      - "3000:3000"