version: '3'
services:
  prova-ruby:
    build:
      context: ./
      dockerfile: .docker/ruby/Dockerfile
    restart: always

    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
  prova-angular:
    build:
      context: ./
      dockerfile: .docker/angular/Dockerfile
    restart: always

    command: ng serve --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./gui:/myapp
